"""
tools/memory.py — Persistent coaching memory

Two layers:
  1. Weekly memos — narrative arc of what happened each week
  2. Athlete profile — evolving model of the athlete: patterns, tendencies, history

Both are generated by Claude and included in every agent context call.
"""

from __future__ import annotations

import json
import logging
import os
from datetime import timedelta
from pathlib import Path

from utils import local_now

import anthropic
from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger(__name__)

PROFILE_FILE = Path(__file__).parent.parent / "data" / "athlete_profile.json"
NOTES_FILE = Path(__file__).parent.parent / "data" / "coaching_notes.json"
MODEL = "claude-opus-4-5"
MEMOS_IN_CONTEXT = 6  # how many recent weekly memos to include in every message

client = anthropic.Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))


# ---------------------------------------------------------------------------
# Persistence
# ---------------------------------------------------------------------------

def load_profile() -> dict:
    if not PROFILE_FILE.exists():
        return {"last_updated": None, "profile": ""}
    with open(PROFILE_FILE, "r") as f:
        return json.load(f)


def save_profile(data: dict) -> None:
    with open(PROFILE_FILE, "w") as f:
        json.dump(data, f, indent=2)


def load_memos() -> list[dict]:
    if not NOTES_FILE.exists():
        return []
    with open(NOTES_FILE, "r") as f:
        return json.load(f).get("memos", [])


def save_memos(memos: list[dict]) -> None:
    with open(NOTES_FILE, "w") as f:
        json.dump({"memos": memos}, f, indent=2)


def append_memo(memo: dict) -> None:
    memos = load_memos()
    memos.append(memo)
    save_memos(memos)
    logger.info(f"Coaching memo saved for week of {memo.get('week_of')}.")


# ---------------------------------------------------------------------------
# Context formatters (used by agent.py)
# ---------------------------------------------------------------------------

def format_profile_for_context() -> str:
    data = load_profile()
    profile = data.get("profile", "")
    updated = data.get("last_updated", "never")
    if not profile:
        return "  No athlete profile built yet."
    return f"  (last updated {updated})\n  {profile}"


def format_recent_memos_for_context() -> str:
    memos = load_memos()
    if not memos:
        return "  No weekly memos yet — builds after first full week."
    recent = memos[-MEMOS_IN_CONTEXT:]
    lines = []
    for memo in recent:
        lines.append(f"  Week of {memo['week_of']}: {memo['memo']}")
    return "\n\n".join(lines)


# ---------------------------------------------------------------------------
# Generation
# ---------------------------------------------------------------------------

def generate_weekly_memo(
    week_of: str,
    activities: list[dict],
    activity_log: list[dict],
    health_log: list[dict],
    plan: dict | None,
    fatigue: dict,
    phase_context: dict | None = None,
    weekly_vert_ft: int = 0,
    vert_target_ft: int = 0,
) -> str:
    """
    Ask Claude to write a 150-word coaching memo summarizing the past week.
    Returns the memo text and saves it.
    """
    existing_profile = load_profile().get("profile", "No profile yet.")

    activity_summary = "\n".join(
        f"  {a['date']} — {a['distance_miles']:.1f}mi | {a['effort']}"
        + (f" | {a.get('elevation_gain_meters',0):.0f}m gain" if a.get('elevation_gain_meters') else "")
        for a in activities
    ) or "  No activities logged."

    checkin_summary = "\n".join(
        f"  {e['date']} — sleep {e.get('sleep_hours','?')}hrs "
        f"(quality {e.get('sleep_quality','?')}/5) | "
        f"legs: {e.get('legs','?')} | stress: {e.get('stress','?')}"
        for e in activity_log
    ) or "  No check-in data."

    health_summary = "\n".join(
        f"  {e['date']} — {e.get('weight_lbs','?')}lbs | {e.get('sleep_hours','?')}hrs sleep"
        for e in health_log
    ) or "  No health data."

    planned = json.dumps(plan.get("days", {}) if plan else {}, indent=2)

    phase = (phase_context or {}).get("phase", "unknown")
    race_name = (phase_context or {}).get("race_name") or "no race registered"
    weeks_to_race = (phase_context or {}).get("weeks_to_race")
    phase_line = (
        f"Phase: {phase} | {weeks_to_race:.0f} weeks to {race_name}"
        if weeks_to_race is not None
        else f"Phase: {phase}"
    )
    vert_line = (
        f"Weekly vert: {weekly_vert_ft:,}ft actual / {vert_target_ft:,}ft target"
        if vert_target_ft
        else f"Weekly vert: {weekly_vert_ft:,}ft"
    )

    prompt = (
        "You are an elite ultramarathon coach writing a weekly coaching memo for your athlete file. "
        "This memo will be included in every future conversation to give you persistent memory of the athlete's history.\n\n"
        "Write a memo of exactly 150 words or less. Be specific and factual. "
        "Focus on: what actually happened vs what was planned, how the athlete felt, "
        "vertical gain adherence vs target, current training phase progression, "
        "any patterns emerging, what to watch for next week, and one key takeaway.\n\n"
        f"Week of: {week_of}\n"
        f"{phase_line}\n"
        f"{vert_line}\n\n"
        f"Planned workouts:\n{planned}\n\n"
        f"Actual Strava activities:\n{activity_summary}\n\n"
        f"Evening check-in data:\n{checkin_summary}\n\n"
        f"Health data (weight/sleep):\n{health_summary}\n\n"
        f"Fatigue: ATL={fatigue['atl']} CTL={fatigue['ctl']} Form={fatigue['form']}\n\n"
        f"Existing athlete profile (for context):\n{existing_profile}\n\n"
        "Write the memo now. No headers, no bullet points — flowing coaching notes."
    )

    response = client.messages.create(
        model=MODEL,
        max_tokens=300,
        messages=[{"role": "user", "content": prompt}],
    )
    memo_text = response.content[0].text.strip()

    append_memo({
        "week_of": week_of,
        "written_at": local_now().strftime("%Y-%m-%d"),
        "memo": memo_text,
    })

    return memo_text


def update_athlete_profile(
    activities: list[dict],
    activity_log: list[dict],
    health_log: list[dict],
    all_memos: list[dict],
) -> str:
    """
    Ask Claude to update the athlete profile based on all accumulated data.
    Returns the updated profile text and saves it.
    Called monthly (or after enough data accumulates).
    """
    existing_profile = load_profile().get("profile", "No profile yet.")

    memos_text = "\n\n".join(
        f"Week of {m['week_of']}: {m['memo']}" for m in all_memos[-12:]
    ) or "No memos yet."

    prompt = (
        "You are an elite ultramarathon coach maintaining a detailed athlete profile. "
        "Based on all available data, write an updated athlete profile of 250 words or less.\n\n"
        "The profile should capture: training patterns and tendencies, life factors that consistently "
        "affect training, strengths, areas to watch, injury history (if any), what motivates this athlete, "
        "what derails them, vertical gain capacity and trends (are they hitting vert targets? "
        "seeking hilly routes or avoiding them?), phase transitions they've navigated, "
        "and any other patterns a coach should always remember.\n\n"
        "Write it as a coach's notes — specific, honest, useful for future planning. "
        "No headers, flowing prose.\n\n"
        f"Current profile:\n{existing_profile}\n\n"
        f"Recent weekly memos:\n{memos_text}\n\n"
        "Write the updated profile now."
    )

    response = client.messages.create(
        model=MODEL,
        max_tokens=500,
        messages=[{"role": "user", "content": prompt}],
    )
    profile_text = response.content[0].text.strip()

    save_profile({
        "last_updated": local_now().strftime("%Y-%m-%d"),
        "profile": profile_text,
    })
    logger.info("Athlete profile updated.")
    return profile_text
