"""
tools/memory.py — Persistent coaching memory

Two layers:
  1. Weekly memos — narrative arc of what happened each week
  2. Athlete profile — evolving model of the athlete: patterns, tendencies, history

Both are generated by Claude and included in every agent context call.
"""

from __future__ import annotations

import copy
import json
import logging
import os
from datetime import timedelta
from pathlib import Path

from utils import local_now

import anthropic
from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger(__name__)

PROFILE_FILE = Path(__file__).parent.parent / "data" / "athlete_profile.json"
NOTES_FILE = Path(__file__).parent.parent / "data" / "coaching_notes.json"
MODEL = "claude-opus-4-5"
EXTRACT_MODEL = "claude-haiku-4-5-20251001"
MEMOS_IN_CONTEXT = 6  # how many recent weekly memos to include in every message

client = anthropic.Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))

_EMPTY_FACTS: dict = {
    "personal": {
        "name": None,
        "age": None,
        "weight_lbs": None,
        "family_context": None,
    },
    "race": {
        "name": None,
        "date": None,
        "distance_miles": None,
        "elevation_gain_ft": None,
        "course_type": None,
    },
    "training": {
        "weekly_mileage_target": None,
        "preferences": [],
    },
    "injuries": [],   # [{description, first_mentioned, resolved}]
    "last_week": {
        "planned_miles": None,
        "actual_miles": None,
    },
}


# ---------------------------------------------------------------------------
# Persistence
# ---------------------------------------------------------------------------

def load_profile() -> dict:
    if not PROFILE_FILE.exists():
        return {"last_updated": None, "profile": "", "facts": copy.deepcopy(_EMPTY_FACTS)}
    with open(PROFILE_FILE, "r") as f:
        data = json.load(f)
    if "facts" not in data:
        data["facts"] = copy.deepcopy(_EMPTY_FACTS)
    return data


def save_profile(data: dict) -> None:
    with open(PROFILE_FILE, "w") as f:
        json.dump(data, f, indent=2)


def load_facts() -> dict:
    return load_profile().get("facts", copy.deepcopy(_EMPTY_FACTS))


def save_facts(facts: dict) -> None:
    data = load_profile()
    data["facts"] = facts
    save_profile(data)


def _merge_facts(existing: dict, new_facts: dict) -> dict:
    """Merge extracted facts into existing. Scalars overwrite, lists append (deduped)."""
    result = copy.deepcopy(existing)

    # personal — overwrite any non-None value
    for key in ("name", "age", "weight_lbs", "family_context"):
        val = new_facts.get("personal", {}).get(key)
        if val is not None:
            result["personal"][key] = val

    # race — overwrite any non-None value
    for key in ("name", "date", "distance_miles", "elevation_gain_ft", "course_type"):
        val = new_facts.get("race", {}).get(key)
        if val is not None:
            result["race"][key] = val

    # training — mileage target overwrites; preferences append (deduped)
    target = new_facts.get("training", {}).get("weekly_mileage_target")
    if target is not None:
        result["training"]["weekly_mileage_target"] = target
    for pref in new_facts.get("training", {}).get("new_preferences", []):
        if pref and pref not in result["training"]["preferences"]:
            result["training"]["preferences"].append(pref)

    # injuries — append new (deduped by description), mark resolved
    existing_descs = {inj["description"].lower() for inj in result.get("injuries", [])}
    for inj in new_facts.get("new_injuries", []):
        desc = inj.get("description", "").strip()
        if desc and desc.lower() not in existing_descs:
            result["injuries"].append({
                "description": desc,
                "first_mentioned": inj.get("first_mentioned", local_now().strftime("%Y-%m-%d")),
                "resolved": False,
            })
            existing_descs.add(desc.lower())
    for resolved_desc in new_facts.get("resolved_injuries", []):
        for inj in result["injuries"]:
            if inj["description"].lower() == resolved_desc.lower():
                inj["resolved"] = True

    # last_week
    for key in ("planned_miles", "actual_miles"):
        val = new_facts.get("last_week", {}).get(key)
        if val is not None:
            result["last_week"][key] = val

    return result


def extract_and_update_facts(user_text: str, assistant_text: str) -> None:
    """
    Extract memorable facts from a conversation exchange and merge into the profile.
    Designed to fail silently — never blocks the main conversation flow.
    """
    try:
        facts = load_facts()
        today = local_now().strftime("%Y-%m-%d")

        prompt = (
            "Extract key facts from this coaching conversation. "
            "Return ONLY a JSON object with the fields you found — omit anything not explicitly mentioned.\n\n"
            "Schema (all fields optional):\n"
            "{\n"
            '  "personal": {"name": str, "age": int, "weight_lbs": float, "family_context": str},\n'
            '  "race": {"name": str, "date": "YYYY-MM-DD", "distance_miles": float, '
            '"elevation_gain_ft": int, "course_type": str},\n'
            '  "training": {"weekly_mileage_target": float, "new_preferences": [str]},\n'
            '  "new_injuries": [{"description": str, "first_mentioned": "YYYY-MM-DD"}],\n'
            '  "resolved_injuries": [str],\n'
            '  "last_week": {"planned_miles": float, "actual_miles": float}\n'
            "}\n\n"
            f"Today: {today}\n\n"
            f"User: {user_text}\n\n"
            f"Coach: {assistant_text}\n\n"
            "Return {} if nothing worth remembering was mentioned. Return only valid JSON, no prose."
        )

        response = client.messages.create(
            model=EXTRACT_MODEL,
            max_tokens=300,
            messages=[{"role": "user", "content": prompt}],
        )

        raw = response.content[0].text.strip()
        if not raw or raw == "{}":
            return

        new_facts = json.loads(raw)
        if new_facts:
            merged = _merge_facts(facts, new_facts)
            save_facts(merged)
            logger.info("Athlete facts updated from conversation.")

    except Exception as e:
        logger.warning(f"Fact extraction failed (non-critical): {e}")


def load_memos() -> list[dict]:
    if not NOTES_FILE.exists():
        return []
    with open(NOTES_FILE, "r") as f:
        return json.load(f).get("memos", [])


def save_memos(memos: list[dict]) -> None:
    with open(NOTES_FILE, "w") as f:
        json.dump({"memos": memos}, f, indent=2)


def append_memo(memo: dict) -> None:
    memos = load_memos()
    memos.append(memo)
    save_memos(memos)
    logger.info(f"Coaching memo saved for week of {memo.get('week_of')}.")


# ---------------------------------------------------------------------------
# Context formatters (used by agent.py)
# ---------------------------------------------------------------------------

def format_profile_for_context() -> str:
    data = load_profile()
    facts = data.get("facts", {})
    profile = data.get("profile", "")
    updated = data.get("last_updated", "never")

    lines: list[str] = []

    # --- Structured facts (always shown when present) ---
    personal = facts.get("personal", {})
    personal_parts = []
    if personal.get("name"):
        personal_parts.append(f"Name: {personal['name']}")
    if personal.get("age"):
        personal_parts.append(f"Age: {personal['age']}")
    if personal.get("weight_lbs"):
        personal_parts.append(f"Weight: {personal['weight_lbs']}lbs")
    if personal_parts:
        lines.append("  " + " | ".join(personal_parts))
    if personal.get("family_context"):
        lines.append(f"  Family: {personal['family_context']}")

    race = facts.get("race", {})
    if race.get("name") or race.get("date"):
        race_str = f"  Race: {race.get('name', 'TBD')}"
        if race.get("date"):
            race_str += f" on {race['date']}"
        details = []
        if race.get("distance_miles"):
            details.append(f"{race['distance_miles']}mi")
        if race.get("elevation_gain_ft"):
            details.append(f"~{race['elevation_gain_ft']:,}ft gain")
        if race.get("course_type"):
            details.append(race["course_type"])
        if details:
            race_str += f" ({', '.join(details)})"
        lines.append(race_str)

    training = facts.get("training", {})
    if training.get("weekly_mileage_target"):
        lines.append(f"  Weekly mileage target: {training['weekly_mileage_target']}mi/week")

    active_injuries = [inj for inj in facts.get("injuries", []) if not inj.get("resolved")]
    if active_injuries:
        lines.append("  Active injuries:")
        for inj in active_injuries:
            lines.append(f"    - {inj['description']} (first noted {inj['first_mentioned']})")

    prefs = training.get("preferences", [])
    if prefs:
        lines.append("  Coaching preferences:")
        for pref in prefs:
            lines.append(f"    - {pref}")

    last_week = facts.get("last_week", {})
    if last_week.get("planned_miles") is not None or last_week.get("actual_miles") is not None:
        lines.append(
            f"  Last week: planned {last_week.get('planned_miles', '?')}mi, "
            f"actual {last_week.get('actual_miles', '?')}mi"
        )

    if lines:
        lines.insert(0, "  [Confirmed facts]")
        lines.append("")

    # --- Gaps (shown so Claude knows what to ask about) ---
    gaps = []
    if not race.get("name"):
        gaps.append("target race name")
    if not race.get("date"):
        gaps.append("race date")
    if not race.get("distance_miles"):
        gaps.append("race distance")
    if not race.get("elevation_gain_ft"):
        gaps.append("race elevation gain")
    if not training.get("weekly_mileage_target"):
        gaps.append("weekly mileage target")
    if not personal.get("age"):
        gaps.append("athlete age")
    if not personal.get("weight_lbs"):
        gaps.append("athlete weight")
    if gaps:
        lines.append(f"  [Profile gaps — ask about one per conversation: {', '.join(gaps)}]")
        lines.append("")

    # --- Narrative profile (monthly synthesis) ---
    if profile:
        lines.append(f"  [Coaching profile — last updated {updated}]")
        lines.append(f"  {profile}")
    elif not lines:
        return "  No athlete profile built yet."

    return "\n".join(lines)


def format_recent_memos_for_context() -> str:
    memos = load_memos()
    if not memos:
        return "  No weekly memos yet — builds after first full week."
    recent = memos[-MEMOS_IN_CONTEXT:]
    lines = []
    for memo in recent:
        lines.append(f"  Week of {memo['week_of']}: {memo['memo']}")
    return "\n\n".join(lines)


# ---------------------------------------------------------------------------
# Generation
# ---------------------------------------------------------------------------

def generate_weekly_memo(
    week_of: str,
    activities: list[dict],
    activity_log: list[dict],
    health_log: list[dict],
    plan: dict | None,
    fatigue: dict,
    phase_context: dict | None = None,
    weekly_vert_ft: int = 0,
    vert_target_ft: int = 0,
) -> str:
    """
    Ask Claude to write a 150-word coaching memo summarizing the past week.
    Returns the memo text and saves it.
    """
    existing_profile = load_profile().get("profile", "No profile yet.")

    activity_summary = "\n".join(
        f"  {a['date']} — {a['distance_miles']:.1f}mi | {a['effort']}"
        + (f" | {a.get('elevation_gain_meters',0):.0f}m gain" if a.get('elevation_gain_meters') else "")
        for a in activities
    ) or "  No activities logged."

    checkin_summary = "\n".join(
        f"  {e['date']} — sleep {e.get('sleep_hours','?')}hrs "
        f"(quality {e.get('sleep_quality','?')}/5) | "
        f"legs: {e.get('legs','?')} | stress: {e.get('stress','?')}"
        for e in activity_log
    ) or "  No check-in data."

    health_summary = "\n".join(
        f"  {e['date']} — {e.get('weight_lbs','?')}lbs | {e.get('sleep_hours','?')}hrs sleep"
        for e in health_log
    ) or "  No health data."

    planned = json.dumps(plan.get("days", {}) if plan else {}, indent=2)

    phase = (phase_context or {}).get("phase", "unknown")
    race_name = (phase_context or {}).get("race_name") or "no race registered"
    weeks_to_race = (phase_context or {}).get("weeks_to_race")
    phase_line = (
        f"Phase: {phase} | {weeks_to_race:.0f} weeks to {race_name}"
        if weeks_to_race is not None
        else f"Phase: {phase}"
    )
    vert_line = (
        f"Weekly vert: {weekly_vert_ft:,}ft actual / {vert_target_ft:,}ft target"
        if vert_target_ft
        else f"Weekly vert: {weekly_vert_ft:,}ft"
    )

    prompt = (
        "You are an elite ultramarathon coach writing a weekly coaching memo for your athlete file. "
        "This memo will be included in every future conversation to give you persistent memory of the athlete's history.\n\n"
        "Write a memo of exactly 150 words or less. Be specific and factual. "
        "Focus on: what actually happened vs what was planned, how the athlete felt, "
        "vertical gain adherence vs target, current training phase progression, "
        "any patterns emerging, what to watch for next week, and one key takeaway.\n\n"
        f"Week of: {week_of}\n"
        f"{phase_line}\n"
        f"{vert_line}\n\n"
        f"Planned workouts:\n{planned}\n\n"
        f"Actual Strava activities:\n{activity_summary}\n\n"
        f"Evening check-in data:\n{checkin_summary}\n\n"
        f"Health data (weight/sleep):\n{health_summary}\n\n"
        f"Fatigue: ATL={fatigue['atl']} CTL={fatigue['ctl']} Form={fatigue['form']}\n\n"
        f"Existing athlete profile (for context):\n{existing_profile}\n\n"
        "Write the memo now. No headers, no bullet points — flowing coaching notes."
    )

    response = client.messages.create(
        model=MODEL,
        max_tokens=300,
        messages=[{"role": "user", "content": prompt}],
    )
    memo_text = response.content[0].text.strip()

    append_memo({
        "week_of": week_of,
        "written_at": local_now().strftime("%Y-%m-%d"),
        "memo": memo_text,
    })

    return memo_text


def update_athlete_profile(
    activities: list[dict],
    activity_log: list[dict],
    health_log: list[dict],
    all_memos: list[dict],
) -> str:
    """
    Ask Claude to update the athlete profile based on all accumulated data.
    Returns the updated profile text and saves it.
    Called monthly (or after enough data accumulates).
    """
    existing_profile = load_profile().get("profile", "No profile yet.")

    memos_text = "\n\n".join(
        f"Week of {m['week_of']}: {m['memo']}" for m in all_memos[-12:]
    ) or "No memos yet."

    prompt = (
        "You are an elite ultramarathon coach maintaining a detailed athlete profile. "
        "Based on all available data, write an updated athlete profile of 250 words or less.\n\n"
        "The profile should capture: training patterns and tendencies, life factors that consistently "
        "affect training, strengths, areas to watch, injury history (if any), what motivates this athlete, "
        "what derails them, vertical gain capacity and trends (are they hitting vert targets? "
        "seeking hilly routes or avoiding them?), phase transitions they've navigated, "
        "and any other patterns a coach should always remember.\n\n"
        "Write it as a coach's notes — specific, honest, useful for future planning. "
        "No headers, flowing prose.\n\n"
        f"Current profile:\n{existing_profile}\n\n"
        f"Recent weekly memos:\n{memos_text}\n\n"
        "Write the updated profile now."
    )

    response = client.messages.create(
        model=MODEL,
        max_tokens=500,
        messages=[{"role": "user", "content": prompt}],
    )
    profile_text = response.content[0].text.strip()

    save_profile({
        "last_updated": local_now().strftime("%Y-%m-%d"),
        "profile": profile_text,
    })
    logger.info("Athlete profile updated.")
    return profile_text
